Adding outputs for WaaS
Azure/LAMP pull request #27
Opened 2021-11-05 15:11 UTC by shishir-msft

2021-11-05 19:34 UTC, shishir-msft commented
Test comment.

2021-11-10 06:39 UTC, UmakanthOS commented
Flagging with @naioja. Changes look OK to me.

2021-11-16 07:17 UTC, venu-sivanadham requested changes

2021-11-16 07:22 UTC, shishir-msft commented on azuredeploy.json
> +                "nodeResourceIds": "[resourceId('Microsoft.Compute/virtualMachineScaleSets', variables('lampCommon').vmssName)]"
Yes I did. SKUs are tested along with these changes included.

2021-11-16 07:57 UTC, shishir-msft commented on nested/nfs-ha.json
> +        }
Thanks for pointing out. Reverted.

2021-11-16 07:57 UTC, shishir-msft commented on azuredeploy.json
> +        "lampCommon": {
I'll take it in a separate PR since it is in scope for demo today.

2021-11-16 08:26 UTC, venu-sivanadham approved these changes

2021-11-16 08:29 UTC, merged